services:
  next:
    container_name: maintainr-next
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - DATABASE_URL=postgres://postgres:password@maintainr-db:5432/maintainr
      - HTTPS=false
    volumes:
      - ./next-uploads:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - maintainr
    depends_on:
      - db
    restart: always
  db:
    container_name: maintainr-db
    image: postgres:12.19
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maintainr
    ports:
      - "5432:5432"
    networks:
      - maintainr
    restart: always
networks:
  maintainr: