export const SERVICE_TYPES = {
  oil_change: "Oil Change",
  tire_rotation: "Tire Rotation",
  brakes: "Brakes",
  battery_replacement: "Battery Replacement",
  air_filter_replacement: "Air Filter Replacement",
  cabin_filter_replacement: "Cabin Filter Replacement",
  fuel_filter_replacement: "Fuel Filter Replacement",
  spark_plug_replacement: "Spark Plug Replacement",
  coolant_flush: "Coolant Flush",
  transmission_service: "Transmission Service",
  wheel_alignment: "Wheel Alignment",
  tire_balancing: "Tire Balancing",
  suspension_repair: "Suspension Repair",
  exhaust_system_repair: "Exhaust System Repair",
  air_conditioning_service: "Air Conditioning Service",
  engine_tune_up: "Engine Tune-Up",
  timing_belt_replacement: "Timing Belt Replacement",
  drive_belt_replacement: "Drive Belt Replacement",
  brake_fluid_flush: "Brake Fluid Flush",
  power_steering_fluid_service: "Power Steering Fluid Service",
  wiper_blade_replacement: "Wiper Blade Replacement",
  headlight_replacement: "Headlight Replacement",
  taillight_replacement: "Taillight Replacement",
  window_repair: "Window Repair",
  door_lock_repair: "Door Lock Repair",
  electrical_system_repair: "Electrical System Repair",
  diagnostic_service: "Diagnostic Service",
  emission_test: "Emission Test",
  state_inspection: "State Inspection",
  roadside_assistance: "Roadside Assistance",
  car_wash: "Car Wash",
  detailing: "Detailing",
  paint_touch_up: "Paint Touch-Up",
  rust_protection: "Rust Protection",
  undercoating: "Undercoating",
  fuel_system_service: "Fuel System Service",
  differential_service: "Differential Service",
  transfer_case_service: "Transfer Case Service",
  software_update: "Software Update",
  recall_service: "Recall Service",
  audio_system_service: "Audio System Service",
  navigation_system_service: "Navigation System Service",
  key_fob_battery_replacement: "Key Fob Battery Replacement",
  remote_start_installation: "Remote Start Installation",
  dash_cam_installation: "Dash Cam Installation",
  performance_upgrade: "Performance Upgrade",
  body_repair: "Body Repair",
  windshield_replacement: "Windshield Replacement",
  interior_repair: "Interior Repair",
  tire_repair: "Tire Repair",
  other: "Other",
};
